name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencues
        timeout-minutes: 5
        run: yarn --frozen-lockfile --prefer-offline

      - name: Compile TypeScript
        run: yarn tsc

      - name: ESLint
        run: yarn lint

      - name: Build App
        run: yarn build
